name: Master CI

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup DotNet Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Publish binaries
        run: dotnet publish -c Release --no-build

      - name: Login Container Repository
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REPOSITORY_USERNAME }}
          password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}

      - name: Build And Push Docker Image for WebClient
        uses: docker/build-push-action@v2
        with:
          context: src/Clients/WebClient
          file: src/Clients/WebClient/Dockerfile
          tags: feedlooker/webclient:${{ github.sha }}
          push: true

      - uses: azure/k8s-set-context@v1
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'

      - name: Deploy WebClient
        uses: azure/k8s-deploy@v1
        with:
          namespace: feedlooker-release-a
          manifests: |
            deployments/webclient.yml
          images: |
            feedlooker/webclient:${{ github.sha }}
